name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - matplotlib==3.10.0
      - numpy==2.2.3
      - scipy==1.15.2
